#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jul 06 00:06:46 BST 2026
maven-metadata-paper-repo.xml.lastUpdated=1783292806260
maven-metadata-spigot-repo.xml.error=
maven-metadata-spigot-repo.xml.lastUpdated=1783292806282
